kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-configmaps-global
subjects:
- kind: ServiceAccount
  name: webhook-service-ac
  namespace: default
roleRef:
  kind: ClusterRole
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io