apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: validating-webhook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validating-webhook-server
  template:
    metadata:
      labels:
        app: validating-webhook-server
    spec:
      containers:
      - name: webhook-server
        image: nightfury1204/validating-webhook-try:v1alpha1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
