apiVersion: v1
kind: Service
metadata:
  name: validating-webhook-service
spec:
  selector:
    app: validating-webhook-server
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
